import type { Word } from '../types/word'

// P2 专用 20 词模拟词库（与 V0 验收的 6 词零重叠，V0 那份随正式接线退役）。
// realExamYears 用 'Mock' 占位，不虚构真实真题年份。
export const MOCK_VOCABULARY = [
  {
    id: 'advocate',
    text: 'advocate',
    rank: 1,
    phonetic: '/ˈædvəkeɪt/',
    senses: [{ partOfSpeech: 'v.', definition: '提倡；主张' }],
    examples: [{ english: 'They advocate reform of the tax system.', chinese: '他们主张改革税收制度。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'ambiguous',
    text: 'ambiguous',
    rank: 2,
    phonetic: '/æmˈbɪɡjuəs/',
    senses: [{ partOfSpeech: 'adj.', definition: '模棱两可的；含糊不清的' }],
    examples: [{ english: 'His reply was deliberately ambiguous.', chinese: '他的回答故意含糊其辞。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'compensate',
    text: 'compensate',
    rank: 3,
    phonetic: '/ˈkɒmpenseɪt/',
    senses: [{ partOfSpeech: 'v.', definition: '补偿；弥补' }],
    examples: [{ english: 'Nothing can compensate for the lost time.', chinese: '什么都无法弥补失去的时间。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'deteriorate',
    text: 'deteriorate',
    rank: 4,
    phonetic: '/dɪˈtɪəriəreɪt/',
    senses: [{ partOfSpeech: 'v.', definition: '恶化；变坏' }],
    examples: [{ english: 'His health deteriorated rapidly.', chinese: '他的健康状况迅速恶化。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'elaborate',
    text: 'elaborate',
    rank: 5,
    phonetic: '/ɪˈlæbərət/',
    senses: [{ partOfSpeech: 'adj.', definition: '精心制作的；详尽的' }],
    examples: [{ english: 'They made elaborate preparations for the ceremony.', chinese: '他们为典礼做了周密的准备。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'feasible',
    text: 'feasible',
    rank: 6,
    phonetic: '/ˈfiːzəbl/',
    senses: [{ partOfSpeech: 'adj.', definition: '可行的；可能实现的' }],
    examples: [{ english: 'The plan is technically feasible.', chinese: '这个计划在技术上是可行的。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'hypothesis',
    text: 'hypothesis',
    rank: 7,
    phonetic: '/haɪˈpɒθəsɪs/',
    senses: [{ partOfSpeech: 'n.', definition: '假说；假设' }],
    examples: [{ english: 'The experiment confirmed her hypothesis.', chinese: '实验证实了她的假说。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'incentive',
    text: 'incentive',
    rank: 8,
    phonetic: '/ɪnˈsentɪv/',
    senses: [{ partOfSpeech: 'n.', definition: '激励；动机' }],
    examples: [{ english: 'Bonuses act as an incentive to work harder.', chinese: '奖金是努力工作的激励。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'jurisdiction',
    text: 'jurisdiction',
    rank: 9,
    phonetic: '/ˌdʒʊərɪsˈdɪkʃn/',
    senses: [{ partOfSpeech: 'n.', definition: '司法权；管辖范围' }],
    examples: [{ english: 'The case falls outside this court\'s jurisdiction.', chinese: '该案件不在本法院管辖范围内。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'legitimate',
    text: 'legitimate',
    rank: 10,
    phonetic: '/lɪˈdʒɪtɪmət/',
    senses: [{ partOfSpeech: 'adj.', definition: '合法的；正当的' }],
    examples: [{ english: 'They raised a legitimate concern.', chinese: '他们提出了一个正当的顾虑。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'manipulate',
    text: 'manipulate',
    rank: 11,
    phonetic: '/məˈnɪpjuleɪt/',
    senses: [{ partOfSpeech: 'v.', definition: '操纵；控制' }],
    examples: [{ english: 'The data was manipulated to mislead readers.', chinese: '数据被篡改以误导读者。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'notorious',
    text: 'notorious',
    rank: 12,
    phonetic: '/nəʊˈtɔːriəs/',
    senses: [{ partOfSpeech: 'adj.', definition: '臭名昭著的' }],
    examples: [{ english: 'The area is notorious for heavy traffic.', chinese: '该地区因交通拥堵而臭名昭著。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'obsolete',
    text: 'obsolete',
    rank: 13,
    phonetic: '/ˈɒbsəliːt/',
    senses: [{ partOfSpeech: 'adj.', definition: '过时的；废弃的' }],
    examples: [{ english: 'The old system has become obsolete.', chinese: '旧系统已经过时了。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'persistent',
    text: 'persistent',
    rank: 14,
    phonetic: '/pəˈsɪstənt/',
    senses: [{ partOfSpeech: 'adj.', definition: '坚持不懈的；持续的' }],
    examples: [{ english: 'Her persistent effort paid off.', chinese: '她持之以恒的努力得到了回报。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'reluctant',
    text: 'reluctant',
    rank: 15,
    phonetic: '/rɪˈlʌktənt/',
    senses: [{ partOfSpeech: 'adj.', definition: '不情愿的；勉强的' }],
    examples: [{ english: 'He was reluctant to admit the mistake.', chinese: '他不愿承认错误。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'scrutinize',
    text: 'scrutinize',
    rank: 16,
    phonetic: '/ˈskruːtənaɪz/',
    senses: [{ partOfSpeech: 'v.', definition: '仔细审查；细看' }],
    examples: [{ english: 'Auditors scrutinized every transaction.', chinese: '审计员仔细审查了每一笔交易。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'substantial',
    text: 'substantial',
    rank: 17,
    phonetic: '/səbˈstænʃl/',
    senses: [{ partOfSpeech: 'adj.', definition: '大量的；相当大的' }],
    examples: [{ english: 'The project needs substantial investment.', chinese: '该项目需要大量投资。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'undermine',
    text: 'undermine',
    rank: 18,
    phonetic: '/ˌʌndəˈmaɪn/',
    senses: [{ partOfSpeech: 'v.', definition: '削弱；暗中破坏' }],
    examples: [{ english: 'The scandal undermined public trust.', chinese: '丑闻削弱了公众的信任。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'versatile',
    text: 'versatile',
    rank: 19,
    phonetic: '/ˈvɜːsətaɪl/',
    senses: [{ partOfSpeech: 'adj.', definition: '多才多艺的；用途广泛的' }],
    examples: [{ english: 'Eggs are a versatile ingredient.', chinese: '鸡蛋是一种用途广泛的食材。' }],
    realExamYears: ['Mock'],
  },
  {
    id: 'warrant',
    text: 'warrant',
    rank: 20,
    phonetic: '/ˈwɒrənt/',
    senses: [{ partOfSpeech: 'v.', definition: '使显得必要；保证' }],
    examples: [{ english: 'The situation warrants immediate action.', chinese: '形势需要立即采取行动。' }],
    realExamYears: ['Mock'],
  },
] as const satisfies readonly Word[]
