/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<
      'Home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '404': RouteRecordInfo<
      '404',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    'Progress': RouteRecordInfo<
      'Progress',
      '/progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Settings': RouteRecordInfo<
      'Settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Study': RouteRecordInfo<
      'Study',
      '/study',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'StudyComplete': RouteRecordInfo<
      'StudyComplete',
      '/study/complete',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Tokens': RouteRecordInfo<
      'Tokens',
      '/tokens',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'Home'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '404'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/progress/index.vue': {
      routes:
        | 'Progress'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | 'Settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/study/index.vue': {
      routes:
        | 'Study'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/study/complete.vue': {
      routes:
        | 'StudyComplete'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tokens/index.vue': {
      routes:
        | 'Tokens'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
